# -*- coding: utf-8 -*-
"""UAS PAA BUBBLE/INSERTION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZmaoAIopZwrqApeGNhttMOKX5EO79Ju
"""

import time

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

def print_iteration(arr, sort_type):
    print(f"5 iterasi pertama {sort_type}: {arr[:5]}")
    print(f"5 iterasi terakhir {sort_type}: {arr[-5:]}")

# List yang diberikan
lst = [12, 99, 62, 15, 20, 95, 39, 48, 3, 24, 8, 43, 74, 19, 97, 33, 49, 68, 55, 33, 90, 90, 7, 26, 85, 46, 39, 40, 9, 36, 60, 64, 89, 31, 25, 71, 21, 23, 63, 84, 32, 5, 3, 44, 21, 10, 21, 17, 50, 2, 36, 53, 79, 54, 19, 88, 1, 32, 31, 15, 6, 3, 1, 40, 22, 43, 18, 1, 77, 9, 59, 40, 7, 41, 81]

print("Sebelum pengurutan:")
print(lst)

choice = input("Pilih metode pengurutan (bubble/insertion): ")
if choice == "bubble":
    start_time = time.time()
    bubble_sort(lst)
    end_time = time.time()
    sort_type = "Bubble Sort"
elif choice == "insertion":
    start_time = time.time()
    insertion_sort(lst)
    end_time = time.time()
    sort_type = "Insertion Sort"
else:
    print("Pilihan tidak valid.")
    exit()

print("Setelah pengurutan:")
print(lst)

print(f"\nHasil 5 iterasi pertama dan 5 iterasi terakhir {sort_type}:")
print_iteration(lst, sort_type)

execution_time = end_time - start_time
print(f"\nWaktu komputasi pengurutan {sort_type}: {execution_time} detik")

# Analisis algoritma
n = len(lst)
worst_case = (n-1) * n // 2
best_case = n - 1
average_case = (worst_case + best_case) // 2

print("\nAnalysis Algorithm:")
print(f"Worst case: {worst_case} perbandingan")
print(f"Best case: {best_case} perbandingan")
print(f"Average case: {average_case} perbandingan")